### ISSUE TITLE
EPIC - Enhance Knative Eventing Integration - Q4 Milestone

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-kogito-serverless-operator#438]
### Description

Knative Eventing plays a huge part in SonataFlow Operator use cases:

- Identify topologies to integrate with Knative Eventing resources
- Identify event integration by analyzing the SonataFlow CR flow definition

As a user, I should be able to deploy a workflow that can produce or consume CloudEvents using the Knative Eventing platform. P2P or Broadcast communications should be considered.

This issue includes:

- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/368
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/355
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/369
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/541
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/521
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/547
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/554

**Comment by jianrongzhang89** [comment]
Working on https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/368.
